Feature/jdyer fix env init
SBNSoftware/sbnana pull request #111
Opened 2024-08-15 18:53 UTC by jamiecd

These changes allow the python environment needed for ICARUS BSM dimuon analyses to be built out-of-the-box.
Additionally, I made a change to how the "branch" track is chosen in the preselection. This change corrects the logic so that it is consistent with how the preselection is described. A study was done previously that verifies that the earlier incorrect logic did not result in different branch tracks being selected (see eg SBN-docdb-37044).

2024-08-15 19:34 UTC, gputnam commented on sbnana/SBNAna/icarus-analysis-villiage/pyana/pyanalib/ntuple_glob.py
Could you uncomment these lines? I think you do still want them in.

2024-08-15 19:34 UTC, gputnam requested changes
Looks good! Just would ask to uncomment the one thing

2024-08-15 20:22 UTC, jamiecd commented
done!

2024-08-21 17:29 UTC, gputnam approved these changes

2024-08-21 17:29 UTC, merged