Adding TruthVar
SBNSoftware/sbnana pull request #113
Opened 2024-11-01 14:27 UTC by jedori0228

Adding `TruthVar` which corresponds to `Var` but per `SRTrueInteratcion` not `SRSlice`.  The usage was described in [doc-35174](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=35174).
* When defining an ISyst, both Shift(Slice) and Shift(TrueInteraction) must be defined. If a shift is truth-based, it is recommended to define the behavior at Shift(TrueInteraction), and call this function inside Shift(Slice). example: https://github.com/SBNSoftware/sbnana/blob/f92120a0b7d2d407f9d95255dbe206e1b05e8942/sbnana/SBNAna/Vars/NuMIFlux.cxx#L75-L101
* Also include an update in n-sigma treatment from NSigmasTrees; adding a new constructor that takes a vector of sigmas.

2025-01-23 22:13 UTC, ibsafa commented
@brucehoward-physics thoughts on this? Can you add your review? now that we have working sbnana releases, I want to clear out as many of these as possible. thanks!

2025-02-20 23:20 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/Spectrum.cxx
> +                     const SpillCut& spillcut,
Maybe the shift has already sailed on this one due to people using this in branches as we've gone, but I wonder if it would be somehow "cleaner" to do SpillCut then TruthCut in parallel with the above being SpillVar then (Slice) Var, and similar comment could apply below.

Anyway, I really don't think this matters too much.

2025-02-20 23:21 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/Spectrum.cxx
> +                     const SpillCut& spillcut,
Ah actually looking even further below I think I see the logic is more like TruthCuts then "reco cuts" where SpillCut is kind-of in-between. This is fine.

2025-02-20 23:51 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoaderBase.h
> +    friend bool operator<(const _VarOrMultiVar<T>& a, const _VarOrMultiVar<T>& b) noexcept;
Isn't this just a repeat of Lines 319-320?

2025-04-07 13:08 UTC, jedori0228 commented on sbnana/CAFAna/Core/SpectrumLoaderBase.h
> +    friend bool operator<(const _VarOrMultiVar<T>& a, const _VarOrMultiVar<T>& b) noexcept;
Thanks, this is removed.

2025-08-13 01:27 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/Cut.h
> +namespace caf{class StandardRecord; class SRSpill; class SRTrueInteraction; class SRSlice;}
Double checking, the `-` part of the diff here (`SRSpillTruthBranch`) is just an old, unused class right? I think that's what I recall.

2025-08-13 01:34 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/ISyst.h
> +                       double& weight) const = 0;
Just thinking, is it better to have this a pure virtual or as a do-nothing that can be optionally given an override? Anyway, if others are happy with or even prefer this, then fine!

2025-08-13 01:37 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoaderBase.h
>      virtual void AddReweightableSpectrum(ReweightableSpectrum& spect,
Do we need or want ReweightableSpectrum versions of TruthVars/TruthCuts?

2025-08-13 01:45 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/Var.h
> +  typedef _Var<caf::SRTrueInteractionProxy> TruthVar;
Line 30 above can add to the comment that it's a template for `TruthVar` as well.

2025-08-13 02:25 UTC, brucehoward-physics commented on sbnana/CAFAna/test/test_TruthVar.C
> +#include "sbnana/CAFAna/Core/Binning.h"
Note that I didn't review this test code! Let me know if I should be.

2025-08-13 02:44 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +                    std::cout << " Not filling into this histogram for this slice." << std::endl;
Should say `Not filling into this histogram for this mc.nu` or `Not filling into this histogram for this True Interaction` or etc.

2025-08-13 02:47 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +    for(caf::SRTrueInteractionProxy& nu: sr->mc.nu){
Doesn't it make more sense to check if `fTruthNSigmasTreeDefs` has anything before we loop `nu` ? Maybe not a huge savings but thought I'd bring it up.

2025-08-13 02:52 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +          if(!pass) continue;
Unlike NSigmas tree, we here ask if the nu passes _after_ the SystShift. (Note that the same thing is done in the slice version so it's not just here.)

I'm thinking about if this is actually the way we want it.

I guess if only weight-based systematics are used in the NUniverses Tree we should see the same behaviour.

2025-08-13 12:59 UTC, brucehoward-physics requested changes
I guess I should explicitly say as a "review" note that I have reviewed most of the code and left various comments. At least one of these is less a choice or thought and actually will require changes. So I'm marking this as "Request Changes."

2025-08-13 14:12 UTC, jedori0228 commented on sbnana/CAFAna/Core/Cut.h
> +namespace caf{class StandardRecord; class SRSpill; class SRTrueInteraction; class SRSlice;}
Yes, I see no place where `SRSpillTruthBranch` is used

2025-08-13 14:26 UTC, jedori0228 commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +                break;
This is fixed in the upcoming commit

2025-08-13 14:33 UTC, jedori0228 commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +                    std::cout << " Not filling into this histogram for this slice." << std::endl;
L414 updated to
```
                    std::cout << " Not filling into this histogram for this True Interaction." << std::endl;
```

2025-08-13 14:49 UTC, jedori0228 commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +              if ( treemapIt->first->SaveTruthCutType() ){
I think I wanted an option not lopping and checking reco slices if one is not interested in that. I added
```
// Option for Truth-based Tree; Not looping and checking over reco slices to fill CutType
void SetSaveTruthCutType(bool _b) {fSaveTruthCutType = _b;}
```
so this being optional.

2025-08-13 14:57 UTC, jedori0228 commented on sbnana/CAFAna/Systs/SBNWeightSysts.cxx
> +  double UniverseWeight::operator()(const caf::SRTrueInteractionProxy* nu) const
I updated the `SRSliceProxy` function to use SRTrueInteractionProxy function:
```
  double UniverseWeight::operator()(const caf::SRSliceProxy* sr) const
  {
    if(sr->truth.index < 0) return 1;

    return operator()(&(sr->truth));
  }
```

2025-08-14 15:35 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +                break;
Great!

2025-08-14 15:43 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +              if ( treemapIt->first->SaveTruthCutType() ){
Okay yeah, if the option is desirable then having a method to set it is good :)

Should there also be a default `true` parameter of the function to set it at construction? Anyway, thanks for clarifying and making it optional.

2025-08-14 15:43 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +                    std::cout << " Not filling into this histogram for this slice." << std::endl;
Great!

2025-08-19 00:54 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +              if ( treemapIt->first->SaveTruthCutType() ){
Thanks for putting in commit `7f9353b` after we spoke earlier today! I think this addresses what I was getting at here. I'm not against the idea of only doing it as a Set/Get method, so if someone else suggests that it should really be that way only then I'm okay going that route.

2025-08-19 01:40 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +    for(caf::SRTrueInteractionProxy& nu: sr->mc.nu){
Looks good!

2025-08-19 01:41 UTC, brucehoward-physics commented on sbnana/CAFAna/Core/SpectrumLoader.cxx
> +          if(!pass) continue;
See comment below, this is good to me.

2025-08-19 14:00 UTC, brucehoward-physics approved these changes
I think I'm happy with this PR now, thanks Jaesung and all for this.

I feel like I'm fairly close to this on some level, so I'm not sure if someone else should take a look at the finished product, but anyway I think this now looks pretty good.

I have a few remaining fairly minor comments:

1. I didn't review the test script or if any changes are needed after the changes during this PR. Let me know if I should take a look at that.

2. I noticed that in some places (including already committed code) it says about histograms with the `Rollback` even in the Trees. Oops.

3. I noticed that this have `Erase` commands for Truth Hists with ReweightableSpectra but these weren't made yet so shouldn't do anything. Anyway, I guess this would be useful if someone wants to add such functionality in the future, so I think it should be fine?

and finally, just a note that I do think that the change to how the Sigmas Tree works with separate systematics applied is a change worth noting in patch notes or etc. as this changes the behaviour with respect to before.

2025-08-20 19:28 UTC, jedori0228 commented on sbnana/CAFAna/Core/SpectrumLoaderBase.cxx
> +    fTruthHistWithCutDefs.Erase(spect);
I am not familiar with Reweightable, but one use-case I see is the smearing where we need both reco and truth, so more like a Reco Var stuff? We may update this later when needed

2025-08-20 20:11 UTC, jedori0228 commented
@kjplows This PR is ready to me merged!

2025-09-12 22:59 UTC, merged